# Generated by Django 2.0 on 2019-12-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculadisciplina',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='matriculadisciplina',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(related_name='minhas_turmas', to='core.Aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='core.Aluno'),
        ),
        migrations.DeleteModel(
            name='MatriculaDisciplina',
        ),
    ]
