# Generated by Django 2.0 on 2019-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191215_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], default='A', max_length=2, null=True, verbose_name='Nivel_conciencia'),
        ),
    ]
