# Generated by Django 2.0 on 2019-12-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('material', models.FileField(blank=True, default='material/2019/', null=True, upload_to='material/%Y/', verbose_name='Material')),
                ('aulas_ministradas', models.IntegerField(verbose_name='Aulas ministradas')),
                ('data', models.DateField()),
                ('assunto', models.CharField(max_length=128, verbose_name='Assunto')),
                ('descricao', models.CharField(max_length=128, verbose_name='Descricao')),
                ('frequencia', models.ManyToManyField(related_name='aulas_assistidas', to='core.Aluno')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=128, verbose_name='tirulo')),
                ('descricao', models.CharField(max_length=128, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='ocorecia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula.Ocorrencia'),
        ),
    ]
