# Generated by Django 2.0 on 2019-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='pendente', max_length=14, verbose_name='Satus'),
        ),
    ]
