# Generated by Django 2.0 on 2019-12-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191215_1405'),
        ('aula', '0002_aula_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.Turma'),
            preserve_default=False,
        ),
    ]
